"""
Script to fetch and format NSE stock list for StockSwing.
Fetches from NSE official sources and creates formatted stock ticker data.
"""

import requests
import csv
from io import StringIO

# Common NIFTY index stocks for comprehensive coverage
NIFTY_500_STOCKS = [
    # NIFTY 50 (Already in database, but included for completeness)
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries", "sector": "Oil & Gas", "index": "NIFTY 50"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services", "sector": "IT Services", "index": "NIFTY 50"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank", "sector": "Banking", "index": "NIFTY 50"},
    {"symbol": "INFY.NS", "name": "Infosys", "sector": "IT Services", "index": "NIFTY 50"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank", "sector": "Banking", "index": "NIFTY 50"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever", "sector": "FMCG", "index": "NIFTY 50"},
    {"symbol": "ITC.NS", "name": "ITC Limited", "sector": "FMCG", "index": "NIFTY 50"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "sector": "Banking", "index": "NIFTY 50"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel", "sector": "Telecom", "index": "NIFTY 50"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank", "sector": "Banking", "index": "NIFTY 50"},
    
    # Additional NIFTY stocks
    {"symbol": "AXISBANK.NS", "name": "Axis Bank", "sector": "Banking", "index": "NIFTY 50"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro", "sector": "Construction", "index": "NIFTY 50"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints", "sector": "Paints", "index": "NIFTY 50"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical", "sector": "Pharma", "index": "NIFTY 50"},
    {"symbol": "TITAN.NS", "name": "Titan Company", "sector": "Jewellery", "index": "NIFTY 50"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India", "sector": "FMCG", "index": "NIFTY 50"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement", "sector": "Cement", "index": "NIFTY 50"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance", "sector": "Financial Services", "index": "NIFTY 50"},
    {"symbol": "WIPRO.NS", "name": "Wipro", "sector": "IT Services", "index": "NIFTY 50"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies", "sector": "IT Services", "index": "NIFTY 50"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra", "sector": "IT Services", "index": "NIFTY 50"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel", "sector": "Metals", "index": "NIFTY 50"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation", "sector": "Power", "index": "NIFTY 50"},
    {"symbol": "NTPC.NS", "name": "NTPC Limited", "sector": "Power", "index": "NIFTY 50"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corporation", "sector": "Oil & Gas", "index": "NIFTY 50"},
    {"symbol": "COALINDIA.NS", "name": "Coal India", "sector": "Mining", "index": "NIFTY 50"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank", "sector": "Banking", "index": "NIFTY 50"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv", "sector": "Financial Services", "index": "NIFTY 50"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors", "sector": "Automobile", "index": "NIFTY 50"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries", "sector": "FMCG", "index": "NIFTY 50"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories", "sector": "Pharma", "index": "NIFTY 50"},
    {"symbol": "CIPLA.NS", "name": "Cipla", "sector": "Pharma", "index": "NIFTY 50"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories", "sector": "Pharma", "index": "NIFTY 50"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals", "sector": "Healthcare", "index": "NIFTY 50"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports", "sector": "Infrastructure", "index": "NIFTY 50"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises", "sector": "Diversified", "index": "NIFTY 50"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel", "sector": "Metals", "index": "NIFTY 50"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries", "sector": "Metals", "index": "NIFTY 50"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries", "sector": "Diversified", "index": "NIFTY 50"},
    {"symbol": "UPL.NS", "name": "UPL Limited", "sector": "Chemicals", "index": "NIFTY 50"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum", "sector": "Oil & Gas", "index": "NIFTY 50"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products", "sector": "FMCG", "index": "NIFTY 50"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance", "sector": "Insurance", "index": "NIFTY 50"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance", "sector": "Insurance", "index": "NIFTY 50"},
    
    # NIFTY Next 50 - Top Mid-cap stocks
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy", "sector": "Power", "index": "NIFTY Next 50"},
    {"symbol": "ADANITRANS.NS", "name": "Adani Transmission", "sector": "Power", "index": "NIFTY Next 50"},
    {"symbol": "AMBUJACEM.NS", "name": "Ambuja Cements", "sector": "Cement", "index": "NIFTY Next 50"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank", "sector": "Banking", "index": "NIFTY Next 50"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints", "sector": "Paints", "index": "NIFTY Next 50"},
    {"symbol": "BEL.NS", "name": "Bharat Electronics", "sector": "Defense", "index": "NIFTY Next 50"},
    {"symbol": "BIOCON.NS", "name": "Biocon Limited", "sector": "Pharma", "index": "NIFTY Next 50"},
    {"symbol": "BOSCHLTD.NS", "name": "Bosch Limited", "sector": "Auto Components", "index": "NIFTY Next 50"},
    {"symbol": "CHOLAFIN.NS", "name": "Cholamandalam Investment", "sector": "Financial Services", "index": "NIFTY Next 50"},
    {"symbol": "COLPAL.NS", "name": "Colgate-Palmolive India", "sector": "FMCG", "index": "NIFTY Next 50"},
    {"symbol": "DABUR.NS", "name": "Dabur India", "sector": "FMCG", "index": "NIFTY Next 50"},
    {"symbol": "DLF.NS", "name": "DLF Limited", "sector": "Real Estate", "index": "NIFTY Next 50"},
    {"symbol": "DMART.NS", "name": "Avenue Supermarts (DMart)", "sector": "Retail", "index": "NIFTY Next 50"},
    {"symbol": "GAIL.NS", "name": "GAIL India", "sector": "Oil & Gas", "index": "NIFTY Next 50"},
    {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products", "sector": "FMCG", "index": "NIFTY Next 50"},
    {"symbol": "HAVELLS.NS", "name": "Havells India", "sector": "Electricals", "index": "NIFTY Next 50"},
    {"symbol": "HINDZINC.NS", "name": "Hindustan Zinc", "sector": "Metals", "index": "NIFTY Next 50"},
    {"symbol": "ICICIPRULI.NS", "name": "ICICI Prudential Life", "sector": "Insurance", "index": "NIFTY Next 50"},
    {"symbol": "INDIGO.NS", "name": "InterGlobe Aviation", "sector": "Aviation", "index": "NIFTY Next 50"},
    {"symbol": "IOC.NS", "name": "Indian Oil Corporation", "sector": "Oil & Gas", "index": "NIFTY Next 50"},
    {"symbol": "JINDALSTEL.NS", "name": "Jindal Steel & Power", "sector": "Metals", "index": "NIFTY Next 50"},
    {"symbol": "MARICO.NS", "name": "Marico Limited", "sector": "FMCG", "index": "NIFTY Next 50"},
    {"symbol": "MCDOWELL-N.NS", "name": "United Spirits", "sector": "Beverages", "index": "NIFTY Next 50"},
    {"symbol": "MOTHERSON.NS", "name": "Samvardhana Motherson", "sector": "Auto Components", "index": "NIFTY Next 50"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance", "sector": "Financial Services", "index": "NIFTY Next 50"},
    {"symbol": "NAUKRI.NS", "name": "Info Edge (Naukri.com)", "sector": "Internet", "index": "NIFTY Next 50"},
    {"symbol": "NMDC.NS", "name": "NMDC Limited", "sector": "Mining", "index": "NIFTY Next 50"},
    {"symbol": "PAGEIND.NS", "name": "Page Industries", "sector": "Textiles", "index": "NIFTY Next 50"},
    {"symbol": "PGHH.NS", "name": "Procter & Gamble Health", "sector": "FMCG", "index": "NIFTY Next 50"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries", "sector": "Chemicals", "index": "NIFTY Next 50"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank", "sector": "Banking", "index": "NIFTY Next 50"},
    {"symbol": "SAIL.NS", "name": "Steel Authority of India", "sector": "Metals", "index": "NIFTY Next 50"},
    {"symbol": "SHREECEM.NS", "name": "Shree Cement", "sector": "Cement", "index": "NIFTY Next 50"},
    {"symbol": "SIEMENS.NS", "name": "Siemens Limited", "sector": "Engineering", "index": "NIFTY Next 50"},
    {"symbol": "SRF.NS", "name": "SRF Limited", "sector": "Chemicals", "index": "NIFTY Next 50"},
    {"symbol": "TATAPOWER.NS", "name": "Tata Power", "sector": "Power", "index": "NIFTY Next 50"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals", "sector": "Pharma", "index": "NIFTY Next 50"},
    {"symbol": "UBL.NS", "name": "United Breweries", "sector": "Beverages", "index": "NIFTY Next 50"},
    {"symbol": "VEDL.NS", "name": "Vedanta Limited", "sector": "Metals", "index": "NIFTY Next 50"},
    {"symbol": "ZEEL.NS", "name": "Zee Entertainment", "sector": "Media", "index": "NIFTY Next 50"},
    
    # Additional Popular Mid/Small Cap Stocks
    {"symbol": "AARTIIND.NS", "name": "Aarti Industries", "sector": "Chemicals", "index": "NIFTY 500"},
    {"symbol": "ABFRL.NS", "name": "Aditya Birla Fashion", "sector": "Retail", "index": "NIFTY 500"},
    {"symbol": "ACC.NS", "name": "ACC Limited", "sector": "Cement", "index": "NIFTY 500"},
    {"symbol": "ASHOKLEY.NS", "name": "Ashok Leyland", "sector": "Automobile", "index": "NIFTY 500"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma", "sector": "Pharma", "index": "NIFTY 500"},
    {"symbol": "BAJAJHLDNG.NS", "name": "Bajaj Holdings", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrishna Industries", "sector": "Auto Components", "index": "NIFTY 500"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "BATAINDIA.NS", "name": "Bata India", "sector": "Footwear", "index": "NIFTY 500"},
    {"symbol": "BHARATFORG.NS", "name": "Bharat Forge", "sector": "Auto Components", "index": "NIFTY 500"},
    {"symbol": "BIF.NS", "name": "Birlasoft Limited", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "CANBK.NS", "name": "Canara Bank", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "CHAMBLFERT.NS", "name": "Chambal Fertilizers", "sector": "Fertilizers", "index": "NIFTY 500"},
    {"symbol": "COFORGE.NS", "name": "Coforge Limited", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "CONCOR.NS", "name": "Container Corporation", "sector": "Logistics", "index": "NIFTY 500"},
    {"symbol": "COROMANDEL.NS", "name": "Coromandel International", "sector": "Fertilizers", "index": "NIFTY 500"},
    {"symbol": "CUMMINSIND.NS", "name": "Cummins India", "sector": "Engineering", "index": "NIFTY 500"},
    {"symbol": "ESCORTS.NS", "name": "Escorts Kubota", "sector": "Auto Components", "index": "NIFTY 500"},
    {"symbol": "EXIDEIND.NS", "name": "Exide Industries", "sector": "Auto Components", "index": "NIFTY 500"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "GODREJPROP.NS", "name": "Godrej Properties", "sector": "Real Estate", "index": "NIFTY 500"},
    {"symbol": "HDFCAMC.NS", "name": "HDFC AMC", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "HONAUT.NS", "name": "Honeywell Automation", "sector": "Engineering", "index": "NIFTY 500"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "IGL.NS", "name": "Indraprastha Gas", "sector": "Oil & Gas", "index": "NIFTY 500"},
    {"symbol": "IRCTC.NS", "name": "IRCTC", "sector": "Travel & Tourism", "index": "NIFTY 500"},
    {"symbol": "JUBLFOOD.NS", "name": "Jubilant FoodWorks", "sector": "Restaurants", "index": "NIFTY 500"},
    {"symbol": "L&TFH.NS", "name": "L&T Finance Holdings", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "LICHSGFIN.NS", "name": "LIC Housing Finance", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "LICI.NS", "name": "Life Insurance Corporation", "sector": "Insurance", "index": "NIFTY 500"},
    {"symbol": "LUPIN.NS", "name": "Lupin Limited", "sector": "Pharma", "index": "NIFTY 500"},
    {"symbol": "M&MFIN.NS", "name": "Mahindra & Mahindra Financial", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "MANAPPURAM.NS", "name": "Manappuram Finance", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "MGL.NS", "name": "Mahanagar Gas", "sector": "Oil & Gas", "index": "NIFTY 500"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis Limited", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "MRF.NS", "name": "MRF Limited", "sector": "Auto Components", "index": "NIFTY 500"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty", "sector": "Real Estate", "index": "NIFTY 500"},
    {"symbol": "OFSS.NS", "name": "Oracle Financial Services", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "PETRONET.NS", "name": "Petronet LNG", "sector": "Oil & Gas", "index": "NIFTY 500"},
    {"symbol": "PFC.NS", "name": "Power Finance Corporation", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "PIIND.NS", "name": "PI Industries", "sector": "Chemicals", "index": "NIFTY 500"},
    {"symbol": "PVR.NS", "name": "PVR INOX", "sector": "Entertainment", "index": "NIFTY 500"},
    {"symbol": "RECLTD.NS", "name": "REC Limited", "sector": "Financial Services", "index": "NIFTY 500"},
    {"symbol": "SRF.NS", "name": "SRF Limited", "sector": "Chemicals", "index": "NIFTY 500"},
    {"symbol": "TATACOMM.NS", "name": "Tata Communications", "sector": "Telecom", "index": "NIFTY 500"},
    {"symbol": "TATACHEM.NS", "name": "Tata Chemicals", "sector": "Chemicals", "index": "NIFTY 500"},
    {"symbol": "TATAELXSI.NS", "name": "Tata Elxsi", "sector": "IT Services", "index": "NIFTY 500"},
    {"symbol": "TRENT.NS", "name": "Trent Limited", "sector": "Retail", "index": "NIFTY 500"},
    {"symbol": "TVSMOTOR.NS", "name": "TVS Motor Company", "sector": "Automobile", "index": "NIFTY 500"},
    {"symbol": "UNIONBANK.NS", "name": "Union Bank of India", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "VOLTAS.NS", "name": "Voltas Limited", "sector": "Consumer Durables", "index": "NIFTY 500"},
    {"symbol": "WHIRLPOOL.NS", "name": "Whirlpool of India", "sector": "Consumer Durables", "index": "NIFTY 500"},
    {"symbol": "YESBANK.NS", "name": "Yes Bank", "sector": "Banking", "index": "NIFTY 500"},
    {"symbol": "ZOMATO.NS", "name": "Zomato Limited", "sector": "Internet", "index": "NIFTY 500"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences", "sector": "Pharma", "index": "NIFTY 500"},
]

if __name__ == "__main__":
    print(f"Total NSE stocks in database: {len(NIFTY_500_STOCKS)}")
    
    # Print by sector
    sectors = {}
    for stock in NIFTY_500_STOCKS:
        sector = stock.get("sector", "Unknown")
        sectors[sector] = sectors.get(sector, 0) + 1
    
    print("\nStocks by Sector:")
    for sector, count in sorted(sectors.items(), key=lambda x: x[1], reverse=True):
        print(f"  {sector}: {count}")
